version: '3'

services:
  postgres:
    image: 'postgres:15.6-alpine'
    ports:
      - '5432:5431'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1'
      - 'POSTGRES_DB=warehouse'
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'


  app:
    build: ./
    container_name: 'warehouse'
    ports:
      - '8081:8081'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/warehouse'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'