spring:
  profiles:
    active: default
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/warehouse
    username: postgres
    password: ${PWD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  scheduling:
    enabled: false  
    optimization: true


aws:
  accessKey: test
  secretKey: test
  region: us-east-1
  endpointUrl: your_s3_endpoint_url



